{% set name = "opentelemetry-instrumentation-chromadb" %}
{% set version = "0.40.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_chromadb-{{ version }}.tar.gz
  sha256: b8165d91a770f7d90e84e414bb6ef74965a04feff73adf581b86d434c3e99c68

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api >=1.28.0,<2.0.0
    - opentelemetry-semantic-conventions >=0.50b0
    - opentelemetry-instrumentation >=0.50b0
    - opentelemetry-semantic-conventions-ai 0.4.8
  run_constrained:
    - chromadb >=0.5.0,<0.6.0

test:
  imports:
    - opentelemetry.instrumentation.chromadb
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - chromadb

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry Chroma DB instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
