{% set name = "opentelemetry-instrumentation-chromadb" %}
{% set version = "0.49.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 3bd805b1333028e6470765080f49d6a14129a76a81da8ddf3d284f1970e5ef8d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - poetry-core

  run:
    - python
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.4.13,<0.5
  run_constrained:
    - chromadb >=0.5.0,<0.6.0

# Unable to run tests and check imports, chromadb is not in the main channel.
test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.traceloop.com/openllmetry
  summary: OpenTelemetry Chroma DB instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    This library allows tracing client-side calls to Chroma vector DB sent with the official Chroma library.
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - invalid_url
    - missing_imports_or_run_test_py
